var stagiaires = {
    1: ['shems',true,'https://youtube.com/embed/TPecOXZC-E0','https://i.imgur.com/W9Azeps.png','https://drive.google.com/file/d/1qkuQt7tqCtTA5uXEkmPVqzWHbojdzPAU/view?usp=sharing','Développeur au goût prononcé pour la recherche et la résolution de problématique, je veux développer mes compétences au travers de projets innovants, dans le but de développer mon activité entrepreneuriale. Actuellement en formation développeur web et web mobile chez Human Booster, recherche un stage pour la période 17 Juillet-13 Septembre 2023', 'shems.chelgoui@outlook.com', '07.51.10.04.91', 'https://github.com/F4CTE', 'https://www.linkedin.com/in/schelgoui/', '','','','',''],
    2: ['cindy',true,'https://youtube.com/embed/TMIwlF53rj0','https://i.imgur.com/brVXFXU.png','https://drive.google.com/file/d/1DGbTaj0Au4qHrP3F0392ch5S_iNx9ybx/view?usp=sharing','Dans le cadre de ma formation développeur web et web mobile, Je cherche un stage du 17 Juillet au 13 Septembre 2023. Mes souhaits se portent pour une entreprise authentique avec un engagement pour l’écologie. Le savoir être, la communication et l’entraide sont des points importants. ', 'grisezcindy@gmail.com', '06.45.19.54.09', 'https://github.com/grisez', 'https://www.linkedin.com/in/cindy-grisez-d%C3%A9veloppeur-web/','','','','',''],
    3: ['Théo',true,'https://youtube.com/embed/rkFxglXel5M','https://i.imgur.com/06sDlVx.png','https://drive.google.com/file/d/1zEEu3T_64IPsAwozTRkR58YU-MVmTFOl/view?usp=sharing',"Dans le cadre de ma formation, je suis à la recherche d'un stage de développeur web du 17 Juillet au 13 Septembre 2023. J'aimerais intégrer une grande structure pour me permettre d'améliorer mes compétences techniques et connaître l'environnement d'un développeur en entreprise.",'theomaurin875@gmail.com', '06.33.92.62.58', 'https://github.com/Theyozz', 'https://www.linkedin.com/in/th%C3%A9o-vieilledent-maurin/','','','','',''],
    4: ['Tommy',true,'https://youtube.com/embed/9sbLfu04y3c','https://i.imgur.com/oJeEXmI.png','https://drive.google.com/file/d/1XGjyPUnL2yCp6Rut8LHBOKMpB9H5l0MM/view?usp=sharing',"Actuellement en formation développeur web et web mobile (RNCP niveau 5 / bac+2) chez Human Booster, je suis à la recherche d'un stage du 17/07/23 au 13/09/23. Idéalement, je veux intégrer une équipe soudée dans une entreprise à taille humaine spécialisée dans l'évènementiel, le sport ou la culture.",'tommyserain@yahoo.fr','06.29.59.36.96','https://github.com/TommySerain','https://www.linkedin.com/in/tommy-serain-5097bb223/','','','','',''],
    5: [ 'Noa',true,'https://youtube.com/embed/cmaCRkNpW_E','https://imgur.com/fJZVMaJ.png','https://drive.google.com/file/d/1CQx33qQEryAnBUqBk9DueDidySZJxuT4/view?usp=sharing',"Je suis en ce moment même dans une formation développeur web et web mobile. Afin de valider mon année je dois effectuer un stage en entreprise du 17/07/23 au 13/09/23, je suis donc en parallèle en recherche d'entreprise. Je reste disponible à tout moment pour plus de renseignements sur mon profil.",'noadevdev@gmail.com','indisponible','https://github.com/NoaDev69360/','https://www.linkedin.com/in/noa-ali-guechi','','','','',''],
    6: ['Paul',true,'https://youtube.com/embed/w4gilCLKKtw','https://imgur.com/88RxsHM.png','https://drive.google.com/file/d/1E5bLykXXMF-feB1-ELiFHmp2g8w59HZH/view?usp=sharing',"Je suis à la recherche d'un stage sur la région lyonnaise dans une entreprise de développement web du 17 juillet au 13 septembre 2023 afin de valider ma formation de développeur web et web mobile (RNCP niveau 5 / bac+2) chez Human Booster. J'aimerais intégrer une entreprise fidèle à mes valeurs, qui sont la confiance et la bonne humeur.",'paul.klein43@gmail.com','06.47.73.49.16','https://github.com/PaulKl10','https://www.linkedin.com/in/paul-klein-devweb','','','','',''],
    7: ['Priscilla',false,'videolink','https://imgur.com/FxlrSfA.png','https://drive.google.com/file/d/1OK83QbQK7W1CctBG9KD4ijR0vG-F3hHC/view?usp=sharing',"Dans le cadre de ma formation, je suis en recherche de stage pour la période du 17 juillet au 13 septembre 2023. Je veux développer mes compétences au sein d'une organisation humanitaire, caritative, qui œuvre dans un esprit de service par le numérique",'preendw@gmail.com','','','https://www.linkedin.com/in/priscilladelpierre',"Bonjour, je m’appelle Priscilla et je me forme au métier de développeur web et web mobile :) dans une super promo !", "Mon projet professionnel consiste à intégrer une équipe qui conçoit des solutions à l’usage des organisations à forte valeur de service","J’ai choisi le développement, car lors de mes expériences de bénévolat, nous avons parfois été confrontés à des problématiques pour lesquelles une réponse (ou un soutien) aurait pu être apportée grâce aux technologies. Les besoins dans ce secteur restent énormes et les perspectives enrichissantes","D’après un test de positionnement, mes forces et talents résident dans un sens de l’innovation, de la collaboration appuyés par des capacités d’autonomie.","Avant le dév’, j’ai surtout occupé des postes administratifs, dans le privé comme dans le public ; et en parallèle à mon activité professionnelle, j’ai pris l’habitude d’œuvrer dans des associations de lutte contre la précarité, l’isolement, la pauvreté."],
    8: ['Romain',true,'https://www.youtube.com/embed/76puzyHTlSw','https://imgur.com/NTcCM3z.png','https://drive.google.com/file/d/13PF6EITi54JnxiQnLxrNhXP9YnpMVBaC/view?usp=sharing',"Enthousiaste et déterminé, je recherche un stage de 2 mois du 17/07/23 au 13/09/23 pour parfaire mon développement, idéalement dans une équipe qui permette de toucher un peu à tout. Passionné par le spatial et les nouvelles technologies, mon dynamisme et ma minutie sont ce que vous recherchez !",'romain.touchet@protonmail.com','06.22.43.21.48','https://github.com/Lunesombre','https://www.linkedin.com/in/romain-touchet-développeur-web','','','','',''],
    9: ['mounir', true,'https://youtube.com/embed/4GGzNi2ZdNg',"https://imgur.com/WcHWEwx.png",'https://drive.google.com/file/d/11XgzdXo7APu-sTYJWO6Yn4ptkwe5V6YI/view?usp=sharing',"Je suis actuellement en formation afin d'obtenir le titre professionnel de Développeur Web et Web Mobile chez Human Booster","mounir.ouazzi.ga@gmail.com",'indisponible', "https://github.com/mounir-o", "https://www.linkedin.com/in/mounirouazzi/",'','','','',''],
    10:['Mohamed',true,"https://youtube.com/embed/ZJ-SIst-Hv0","https://imgur.com/VVpWZrJ.png",'https://drive.google.com/file/d/13ZO1yocq7lfYlusNV4uGRNOj4_5OErm-/view?usp=sharing'," Français, tunisien et égyptien.Trouver un stage, tu dois. Du 17/07 au 13/09, il le faut.» Me Yoda.Curieux, compétiteur et sociable, j'aime mon métier et le piment. Attention, ma bonne humeur est contagieuse.","djebali.mohamed88@gmail.com", "06.09.67.26.93", "https://github.com/Nouster", "https://www.linkedin.com/in/mohamed-djebali-developpeur-web",'','','','',''],
    11:['mickael',true,"https://youtube.com/embed/bqgboDyY_vg","https://imgur.com/gFTsP13.png",'https://drive.google.com/file/d/1czClWI2rWfdygAzcm-agJ3HnZZJ0mC9-/view?usp=sharing',"Passionné par l'informatique depuis mon plus jeune âge, j'ai le projet d'en faire mon métier. Je suis actuellement en formation de développeur web et web mobile.Dans le cadre de ma formation professionnelle je recherche un stage pour la période de juillet 2023.","madallstar@gmail.com", '06.20.14.57.90', 'https://github.com/Mickael972', "https://www.linkedin.com/in/mickaël-juste-développeurweb",'','','','','',],
    12:['Maxence',true,"https://youtube.com/embed/Duk9KDTesvs","https://imgur.com/vFLFGLR.png",'https://drive.google.com/file/d/1ERTQ1aJZDFo9Ro9pLAUHp5YrMgBEzcDx/view?usp=sharing',"Pour valider ma formation professionnelle, je recherche un stage afin d'accroître mes connaissances et développer mes compétences, en travaillant au sein d'une équipe dynamique et partageuse.Date de stage : du 17 Juillet au 13 Septembre 2023","maxence.leduc@yahoo.com", "0666502554", "https://github.com/Max-ldc", "https://www.linkedin.com/in/maxence-leduc-devweb",'','','','',''],
    13: ['adile',false,'videoLink','https://i.imgur.com/s42ZngF.png','cvLink','Vous êtes à la recherche d’un stagiaire en développement web du 17 juillet au 13 septembre 2022 /? Ne cherchez plus, je suis là. Je serais heureux de mettre mes connaissances et mes compétences au sein de votre entreprise. Je suis disponible pour vous rencontrer afin de vous en dire plus.','adile.humanbooster@gmail.com','','','',"Je m'appelle Adile et j'ai 44 ans.","Je choisis le monde du digital et plus particulièrement le développement car j'aime le côté construction et élaboration d'un site ou d'un projet.","Par la suite, j'aimerais créer une Agence Web et proposer mes services à des TPE.","Je suis de nature créative, à l'écoute des clients et toujours connecté.","Je suis un cinéphile, j'aime la découverte de la nature grâce à la randonnée, et je suis un fan de football."],
    14: ['claire',true,'https://youtube.com/embed/ffEnpGcYJP8','https://i.imgur.com/OwLoc6r.png','https://drive.google.com/file/d/1nRy-h5dC9SEmoixEVgip1IGLbzg1m49L/view?usp=sharing',"Je suis actuellement une formation de développeur web & web mobile. Dans ce cadre là, je cherche un stage de 2 mois du 17/09/2023 au 23/09/2023 afin de mettre en pratique mes compétences. Autonome et polyvalente, je souhaite rejoindre une équipe ouverte d’esprit, constituée de passionné(e)s.",'vitsingz@gmail.com','06.58.99.06.57','','https://www.linkedin.com/in/claire-weiqing-zhao-868b4982/',''],
    15: ['dimitri',true,'https://youtube.com/embed/6O_AOWEIho8','https://i.imgur.com/KYnkjUg.png','https://drive.google.com/file/d/1KijbA66-IabDq1IKABu1vENZPP-GMku1/view?usp=sharing',"Actuellement en formation développeur web avec Human Booster où je prépare un titre professionnel (BAC +2).Je recherche un stage en tant que développeur web front-end du 17/07/2023 au 13/09/2023.",'dimitri-bonnet@hotmail.fr','06.20.00.81.45','https://github.com/dimone69000','https://www.linkedin.com/in/dimitri-bonnet-developpeur-web/','','','','',''],
    16: ['erwan',true,'https://youtube.com/embed/N3TQ4wVRVrc','https://i.imgur.com/zbGomHA.png','https://drive.google.com/file/d/1e0Io8EhIJyoqgQzlfY4Y-AxBMBxvJfQ0/view?usp=sharing',"Dans le cadre de ma formation développeur Web avec Human Booster, je suis à la recherche d'un stage du 17 juillet 2023 au 13 septembre 2023 pour valider ma formation. Ce stage me permettrait de mettre en application mes cours théoriques afin de contribuer à l'évolution de l'entreprise. Par ailleurs, ce stage est primordial pour comprendre complètement le métier. De nature très curieux et dynamique, je suis déterminé à apprendre pendant ce stage.",'didillon.erwan@gmail.com','06.66.11.96.47','https://github.com/iNeZiiaaH','https://www.linkedin.com/in/erwan-didillon-d%C3%A9veloppeurweb/','','','','',''],
};



const queryString = window.location.search;
const urlParams = new URLSearchParams(queryString);
const id = urlParams.get('param1');
document.getElementById("prenom").innerText=stagiaires[id][0];
document.getElementById("phrase-accroche").innerText=stagiaires[id][5];
document.getElementById("recto-carte").src=stagiaires[id][3];
document.getElementById("reponse1").innerText=stagiaires[id][10];
document.getElementById("reponse2").innerText=stagiaires[id][11];
document.getElementById("reponse3").innerText=stagiaires[id][12];
document.getElementById("reponse4").innerText=stagiaires[id][13];
document.getElementById("reponse5").innerText=stagiaires[id][14];